# Generated by Django 2.0.2 on 2018-09-06 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='comments',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
