# Generated by Django 2.0.2 on 2018-09-06 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_answer_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='comments',
            field=models.CharField(default='', max_length=255),
        ),
    ]
