# Generated by Django 2.0.2 on 2018-09-15 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_auto_20180906_0450'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='desired_mean_word_length',
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name='question',
            name='desired_mean_words_per_sentence',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='question',
            name='expanded_keywords',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='question',
            name='keywords',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='question',
            name='max_word_count_penalty',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='question',
            name='max_word_length_penalty',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='question',
            name='max_words_per_sentence_penalty',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='question',
            name='min_word_count',
            field=models.IntegerField(default=150),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('ES', 'Essay'), ('PS', 'Picture Story'), ('CP', 'Connect the phrases'), ('UW', 'Use words')], default='ES', max_length=2),
        ),
    ]
