# Generated by Django 2.0.2 on 2018-09-15 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_auto_20180915_0749'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='picture',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
