# Generated by Django 2.0.2 on 2018-09-15 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_question_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='keywords',
            field=models.TextField(blank=True, default=''),
        ),
    ]
