# Generated by Django 2.0.2 on 2018-09-15 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_auto_20180915_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='expanded_keywords',
            field=models.TextField(blank=True, default=''),
        ),
    ]
