# Generated by Django 2.0.2 on 2018-09-15 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_auto_20180915_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='picture',
            field=models.ImageField(default='/standard/es.jpg', upload_to=''),
        ),
    ]
